version: "3.8"

services:
  nginx:
    build: ./
    restart: always
    ports:
      - 80:8080
      - 443:443
    volumes:
      - /etc/ssl:/etc/ssl:ro
      - ./docker/nginx_conf.d/:/etc/nginx/conf.d/:ro
